name: Publish

on:
  workflow_dispatch:
    inputs:
      segment:
        description: "The version segment to increment: major, minor, patch, premajor, preminor, prepatch, or prerelease."
        required: true
      preId:
        description: "Appended to the pre-release segment. (default: \"\")"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: "Install"
        run: npm ci

      - name: "Build"
        run: npm run build

      - name: "Test"
        run: npm run buildtests && npm run test

      - name: Increment Version
        run: |
          git config --local user.email "Workflow: ${{ env.GITHUB_WORKFLOW }}[bot]"
          git config --local user.name "${{ env.GITHUB_WORKFLOW }}[bot]@workflow"

          if [[ ${{ github.event.inputs.segment }} == pre* ]]; then
            PRE_ID="${{ github.event.inputs.preId}}"
            if [[ -n "$PRE_ID" ]]; then
              PRE_ID_COMMAND_STR="--preid $PRE_ID"
            fi
          fi
          npm version ${{ github.event.inputs.segment }} $PRE_ID_COMMAND_STR -m "Publish v%s"

      - name: Publish to NPM Registry
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}

      - name: Push Tag
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          # branch: ${{ github.ref }} change this for testing
          branch: ${{ github.ref }}
          tags: true
